# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'mmitchell+standard@box.com'
  config.password       = 'demo1234'
  config.integrator_key = 'PLAT-b936af25-0caa-42f8-b565-12b3eb264352'
  config.account_id     = '1254430'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end
