# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'cburnette@box.com'
  config.password       = 'time4tea'
  config.integrator_key = 'FINA-2bad235d-e167-467c-94a4-2b853493636d'
  config.account_id     = '993092'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

